title: Einstehen für Olten – JA zum Budget
url: https://einstehen-für-olten.ch
site:
  lang: de
sass:
    style: compressed
    sass_dir: _sass

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
