title: Einstehen für Olten – JA zum Budget 2022
description: Überparteiliches Unterstützungskomitee
site:
  lang: de
sass:
    style: compressed
    sass_dir: _sass

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
